# golangci-lint configuration for dendrite-pulse (v2.5.0)
version: 2

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    # Bug detection & correctness
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - nilerr
    - bodyclose
    - sqlclosecheck
    - contextcheck
    - copyloopvar

    # Error handling
    - errorlint
    - wrapcheck

    # Security
    - gosec

    # Code quality & performance
    - gocritic
    - gocyclo
    - gocognit
    - unconvert
    - unparam
    - unused
    - prealloc
    - exhaustive

    # Maintainability
    - dupl
    - funlen
    - maintidx

    # Style
    - revive
    - misspell
    - lll
    - goconst
    - gochecknoinits
    - nolintlint

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - gocognit
        - gosec
        - goconst
        - lll
        - funlen
        - dupl
        - wrapcheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  funlen:
    lines: 80
    statements: 50

  dupl:
    threshold: 100

  goconst:
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - whyNoLint  # Covered by nolintlint

  lll:
    line-length: 120
    tab-width: 4

  misspell:
    locale: US

  exhaustive:
    default-signifies-exhaustive: true

  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: exported
      - name: var-naming
      - name: receiver-naming
      - name: error-strings
      - name: error-return
      - name: indent-error-flow
      - name: early-return
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: time-naming
      - name: unreachable-code

  gosec:
    severity: medium
    confidence: medium

  wrapcheck:
    ignore-sigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
